export enum KafkaTopics {
  TOPIC_RECEIVE_ACTIVITY = 'TOPIC_RECEIVE_ACTIVITY',
  TOPIC_PERFORM_MATCHING_RULES = 'TOPIC_PERFORM_MATCHING_RULES',
  TOPIC_CAMPAIGN_REWARD = 'TOPIC_CAMPAIGN_REWARD',
  TOPIC_PERFORM_SCHEDULED_CAMPAIGN = 'TOPIC_PERFORM_SCHEDULED_CAMPAIGN'
}
